FROM arm32v7/alpine:3.10
LABEL maintainer "Ming Chen<mingcheng@outlook.com>" architecture="ARM32v7/armhf"

ENV VERSION=1.0.1
ENV PACKAGE_URL=https://github.com/syncthing/discosrv/releases/download/v${VERSION}/stdiscosrv-linux-arm-v${VERSION}.tar.gz

RUN wget $PACKAGE_URL && \
  tar zxf stdiscosrv-linux-arm-v${VERSION}.tar.gz && \
  mv stdiscosrv-linux-arm-v${VERSION}/stdiscosrv /bin/stdiscosrv && \
  rm -rf stdiscosrv-linux-arm-v${VERSION}*

EXPOSE 8443
USER nobody
ENTRYPOINT [ "/bin/stdiscosrv" ]
