FROM arm32v7/alpine:3.10
LABEL maintainer "Ming Chen<mingcheng@outlook.com>" architecture="ARM32v7/armhf"

ENV VERSION=1.0.1
ENV PACKAGE_URL=https://github.com/syncthing/relaysrv/releases/download/v${VERSION}/strelaysrv-linux-arm-v${VERSION}.tar.gz

RUN wget $PACKAGE_URL && \
  tar zxf strelaysrv-linux-arm-v${VERSION}.tar.gz && \
  mv strelaysrv-linux-arm-v${VERSION}/strelaysrv /bin/strelaysrv && \
  rm -rf strelaysrv-linux-arm-v${VERSION}*

EXPOSE 22067 22070
USER nobody
ENTRYPOINT [ "/bin/strelaysrv" ]
